=== dariusz4424/ModernAdatbazisRendszerek/Beadando_XML_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="Raktar_DB">
    <xs:complexType>
        <xs:sequence>
            
            <!-- Epulet eleje -->
            <xs:element name="Epulet" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        
                        <!-- Epulet reszletei -->
                        
                        <xs:element name="Lokacio_kod" type="xs:int"/>
                        <xs:element name="Cim">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="IrSzam" type="xs:int"/>
                                    <xs:element name="Varos" type="xs:string"/>
                                    <xs:element name="Utca" type="xs:string"/>
                                    <xs:element name="Hazszam" type="xs:int"/>
                                </xs:sequence>                                
                            </xs:complexType>
                        </xs:element>
                        
                        <!-- Salgo polc, Epuleten belul -->
                        
                        <xs:element name="Salgo_polc" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Sor" type="xs:int"/>
                                    <xs:element name="Oszlop" type="xs:int"/>
                                    
                                    <!-- Pozicio Salgo_polcon belul -->
                                    
                                    <xs:element name="Pozicio" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="Sorszam" type="xs:int"/>
                                            </xs:sequence>
                                            <xs:attribute name="pid" type="xs:string"/>
                                        </xs:complexType>
                                    </xs:element>                                    
                                </xs:sequence>
                                <xs:attribute name="spid" type="xs:string"/>
                            </xs:complexType>
                        </xs:element>                        
                    </xs:sequence>
                    <xs:attribute name="eid" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <!-- Epulet vege -->
            
            <!-- Beszallito eleje -->
            <xs:element name="Beszallito" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        
                        <!-- Beszallito reszletei -->
                        <xs:element name="Nev" type="xs:string"/>
                        <xs:element name="Elerhetoseg" type="xs:string"/>
                        <xs:element name="Cim">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="IrSzam" type="xs:int"/>
                                    <xs:element name="Varos" type="xs:string"/>
                                    <xs:element name="Utca" type="xs:string"/>
                                    <xs:element name="Hazszam" type="xs:int"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        
                        <!-- Termek, a Beszalliton belul -->
                        <xs:element name="Termek" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Megnevezes" type="xs:string"/>
                                    <xs:element name="Tipus" type="xs:string"/>
                                    <xs:element name="Ar" type="xs:int"/>
                                    
                                    <!-- Termek pozicio, Termeken belul -->
                                    <xs:element name="Termek_Pozicio" type="xs:int"/>
                                </xs:sequence>
                                <xs:attribute name="tid" type="xs:string"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="bid" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <!-- Beszallito vege -->
            
        </xs:sequence>
    </xs:complexType>
    
    <!-- Primary Keyek-->
    <!-- eid -->
    <xs:key name="PK_eid">
        <xs:selector xpath="Epulet"/>
        <xs:field xpath="@eid"/>
    </xs:key>
    <!-- spid -->
    <xs:key name="PK_spid">
        <xs:selector xpath="Epulet/Salgo_polc"/>
        <xs:field xpath="@spid"/>
    </xs:key>
    <!-- pid -->
    <xs:key name="PK_pid">
        <xs:selector xpath="Epulet/Salgo_polc/Pozicio"/>
        <xs:field xpath="@pid"/>
    </xs:key>
    <!-- bid -->
    <xs:key name="PK_bid">
        <xs:selector xpath="Beszallito"/>
        <xs:field xpath="@bid"/>
    </xs:key>
    <!-- bid -->
    <xs:key name="PK_tid">
        <xs:selector xpath="Beszallito/Termek"/>
        <xs:field xpath="@tid"/>
    </xs:key>
    
    <!-- Foreign Key -->
    <!-- Termek_Pozicio -->
    <xs:keyref refer="PK_pid" name="FK_TPoz">
        <xs:selector xpath="Beszallito/Termek"></xs:selector>
        <xs:field xpath="Beszallito/Termek/Termek_Pozicio"></xs:field>
    </xs:keyref>
</xs:element>
</xs:schema>

=== dariusz4424/ModernAdatbazisRendszerek/Beadando.xml
<?xml version="1.0" encoding="UTF-8"?>
<Raktar_DB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Beadando_XML_Schema.xsd">
    <Epulet eid="1">
        <Lokacio_kod>3768</Lokacio_kod>
        <Cim>
            <IrSzam>8000</IrSzam>
            <Varos>Szekesfehervar</Varos>
            <Utca>Raktar utca</Utca>
            <Hazszam>3</Hazszam>
        </Cim>
        <Salgo_polc spid="1">
            <Sor>1</Sor>
            <Oszlop>1</Oszlop>
            <Pozicio pid="1">
                <Sorszam>1</Sorszam>
            </Pozicio>
            <Pozicio pid="2">
                <Sorszam>2</Sorszam>
            </Pozicio>
            <Pozicio pid="3">
                <Sorszam>3</Sorszam>
            </Pozicio>
            <Pozicio pid="4">
                <Sorszam>4</Sorszam>
            </Pozicio>
            <Pozicio pid="5">
                <Sorszam>5</Sorszam>
            </Pozicio>
        </Salgo_polc>
    </Epulet>
    
    <Beszallito bid="1">
        <Nev>Fehervari 1-es pekseg</Nev>
        <Elerhetoseg>+36 46 345 678</Elerhetoseg>
        <Cim>
            <IrSzam>8000</IrSzam>
            <Varos>Szekesfehervar</Varos>
            <Utca>Kenyersuto utca</Utca>
            <Hazszam>3</Hazszam>
        </Cim>
        <Termek tid="1">
            <Megnevezes>Kenyer</Megnevezes>
            <Tipus>Elelmiszer</Tipus>
            <Ar>550</Ar>
            <Termek_Pozicio>1</Termek_Pozicio>
        </Termek>
        <Termek tid="2">
            <Megnevezes>Zsemle</Megnevezes>
            <Tipus>Elelmiszer</Tipus>
            <Ar>50</Ar>
            <Termek_Pozicio>1</Termek_Pozicio>
        </Termek>
    </Beszallito>
    <Beszallito bid="2">
        <Nev>Harman Becker</Nev>
        <Elerhetoseg>+36 46 765 432</Elerhetoseg>
        <Cim>
            <IrSzam>8000</IrSzam>
            <Varos>Szekesfehervar</Varos>
            <Utca>Amerikai fasor</Utca>
            <Hazszam>15</Hazszam>
        </Cim>
        <Termek tid="3">
            <Megnevezes>Autosradio</Megnevezes>
            <Tipus>Elektronika</Tipus>
            <Ar>400000</Ar>
            <Termek_Pozicio>3</Termek_Pozicio>
        </Termek>
        <Termek tid="4">
            <Megnevezes>Hangszoro</Megnevezes>
            <Tipus>Elektronika</Tipus>
            <Ar>30000</Ar>
            <Termek_Pozicio>4</Termek_Pozicio>
        </Termek>
    </Beszallito>

</Raktar_DB>
